# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGUwj1c7R9QJOoxA2Iyyo-8ydWJGzyR-
"""

def somar(a, b):
    return a+b

def subtrair(a, b):
    return a-b

def multiplicar(a, b):
    return a*b

def dividir(a, b):
    if b != 0:
        return a/b
    else:
        print('Não existe divisão por zero.')
        a = float(input('Digite novamente o numerador: '))
        b = float(input('Digite um denominador diferente de zero: '))
        return dividir(a, b)